selector_dict = {}
selector_dict['signin_btn'] = "xp://a[contains(text(), 'Sign in')]"
selector_dict['login_btn'] = "xp://button[@type = 'submit']"
selector_dict['username_input'] = "xp://input[@name = 'login']"
selector_dict['password_input'] = "xp://input[@name = 'password']"
selector_dict['dashboard_header_div'] = "xp://div[@id = 'sm-action-area']"
selector_dict['nav_security_btn'] = "xp://a[@id = 'first-security']"
selector_dict['nav_backup_btn'] = "xp://div[@id = 'second-security']//a[@data-id = 'sm-backup']"
selector_dict['create_backup_btn'] = "xp://a[contains(text(), 'Create backup')]"
selector_dict['backup_type_zip_btn'] = "xp://select[@name = 'backupType']//option[@value = 'zip']"
selector_dict['effective_create_backup_btn'] = "xp://div[contains(@class, 'form-actions')]//input[@value = 'Create backup']"
selector_dict['refresh_status_btn'] = "xp://a[contains(text(), 'Refresh status')]"
selector_dict['completed_status_div'] = "xp://div[@id = 'sm-action-area']//div[contains(text(), 'Completed')]"
selector_dict['backup_url'] = "xp://a[contains(@href, '.zip')]"
